_target_: flash.image.detection.data.ObjectDetectionData.from_coco

train_folder: "" #data_dir is specified in config.yaml
train_ann_file: ""
val_folder: null
val_ann_file: null
val_split: 0.3
batch_size: 2
