model_checkpoint:
  _target_: pytorch_lightning.callbacks.ModelCheckpoint
  monitor: "val/map50"
  mode: "max"
  save_top_k: 1
  save_last: True
  verbose: False
  dirpath: "checkpoints/"
  filename: "epoch_{epoch:03d}"
  auto_insert_metric_name: False

model_summary:
  _target_: pytorch_lightning.callbacks.RichModelSummary
  max_depth: 4

rich_progress_bar:
  _target_: pytorch_lightning.callbacks.RichProgressBar
